### ISSUE TITLE
Installation doesn't work on Arch Linux. 

### ISSUE THREAD

**Issue by aniketpanjwani** [aniketpanjwani/chomper#20]
##### Steps to reproduce the problem:
May not work on other distros either?

**Comment by aniketpanjwani** [comment]
If you're using arch, try out the iss20 branch and let me know how it goes.

**Comment by aniketpanjwani** [comment]
won't work for arch - need to turn certfile variable in certs.sh into an argument.

**Comment by aniketpanjwani** [comment]
Closing this for now since I have no intention of developing this alone. If you use Arch and are willing to help me develop a new shell script (as discussed here: https://chomper.readthedocs.io/en/latest/installation/index.html), leave a comment and I'll reopen this.

**Comment by michaelKurowski** [comment]
I might help you @aniketpanjwani

**Comment by LinuxFTW** [comment]
Same here!
